### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by David263** [neutralinojs/neutralinojs-javascript#4]
I followed the instructions in the ReadMe here on Windows, but nothing happened. I was expecting to see a window containing "hello world". In the cloned directory on my computer, I don't see an EXE file to run, which is how you run an app on Windows. How do I run a neutrino application? How do I distribute it to users? Is there a tutorial covering these questions? (The npm world is new to me. I tried Electron, and it worked, but it uses a vast amount of memory, and it doesn't seem to have much help available.)

**Comment by David263** [comment]
I found a download Zip file at https://github.com/neutralinojs/neutralinojs/releases. This one contains completely different contents. I'm confused.

**Comment by shalithasuranga** [comment]
Please try the latest version's documentation: https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app
